name: yk_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.1.0
  cached_network_image: ^2.2.0
  shared_preferences: ^0.5.7
  flutter_webview_plugin: ^0.3.11
  share: ^0.6.4
  fluttertoast: ^4.0.1
  battery: ^1.0.1
  intl: ^0.16.1
  device_info: ^0.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^4.0.0
  event_bus: ^2.0.0
  fluro: ^2.0.3
flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
   - family: HotSearch
     fonts:
      - asset: assets/fonts/Lobster-Regular.ttf